version: '3.1'

services:
    app:
        image: '37dbb6e327d1'
        container_name: incload_app
        ports:
            - '127.0.0.1:8080:8080'
        environment:
            - DB_USER=developer
            - DB_URL=jdbc:postgresql://db:5432/incload_db
            - DB_PASSWORD=DeveloperRoot
        depends_on:
            - db
    db:
        image: "postgres"
        container_name: db
        environment:
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=DeveloperRoot